version: '3.4'

services:
  db:
    image: mysql:5.7
    restart: always
    env_file:
      - docker-compose-variables.env
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
      - ./container_database/data:/var/lib/mysql:rw
  pma:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:5.1.1
    restart: always
    ports:
      - "8080:80"
  webserver:
    depends_on:
      - db
    #image: httpd
    env_file:
      - docker-compose-variables.env
    build:
      context: .
      dockerfile: ./container_webserver/dockerfile
    ports:
      - "80:80"
    volumes:
      - ./build/:/var/www:rw
      - ./scripts:/var/www/scripts:rw
      - ./config/composer.json:/var/www/composer.json:rw
    entrypoint:
      [
        "bash",
        "-c",
        "chmod -R 777 /var/www/html/&& cd /var/www && scripts/build-and-deploy.sh -b test && apache2-foreground"
      ]

